name: Monthly Release

on:
  workflow_dispatch:

jobs:
  monthly-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4  
      # setup nodejs
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          
      # Run the npm install          
      - run: npm ci
          
      # Runs a single command using the runners shell
      - name: Run publishing scripts
        run: |
          npm run clean
          npm run package
          npm run just-publish      
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
