name: V4 Pull Request Testing
on:
  pull_request:
    branches:
        - version-4
jobs:
  run_pr_tests:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4  
      # setup nodejs
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          
      # Run the npm install          
      - run: npm ci
      
      - name: Run lint
        run: npm run lint
      
      - name: Run package
        run: npm run package
      
      - name: Run tests
        run: npm test -- --mode pr
